version: "3"
services:
  hub:
    image: seleniarm/hub:4.16
    ports:
      - "4444:4444"
  chrome:
    image: seleniarm/node-chromium:4.16
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
  firefox:
    image: seleniarm/node-firefox:4.16
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
#  tests:
#    image: radulenko/overall-tests
#    depends_on:
#      - chrome
#    environment:
#      - BROWSER=remote
#      - ENV=aqa
#      - SELENIUM_HUB_HOST=hub
#      - SUITES=suits.RegressionSuite
#      - THREAD_COUNT=4
#    volumes:
#      - ./allure-results/test:/home/selemium-docker/allure-results
#
  tests2:
    image: radulenko/overall-tests
    depends_on:
      - firefox
    environment:
      - BROWSER=remote
      - ENV=aqa
      - SELENIUM_HUB_HOST=hub
      - SUITES=suits.SmokeSuite
      - THREAD_COUNT=4
    volumes:
      - ./allure-results/test2:/home/selemium-docker/allure-results
#    command: test