version: "3"
services:

  tests:
    image: radulenko/selenium:latest
    environment:
      - BROWSER=remote
      - ENV
      - SELENIUM_HUB_HOST=hub
      - SUITES
      - THREAD_COUNT=2
    volumes:
      - ./allure-results/test:/home/selemium-docker/allure-results

#  tests2:
#    image: radulenko/overall-tests
#    environment:
#      - BROWSER=remote
#      - ENV=aqa
#      - SELENIUM_HUB_HOST=hub
#      - SUITES=suits.SmokeSuite
#      - THREAD_COUNT=4
#    volumes:
#      - ./allure-results/test2:/home/selemium-docker/allure-results
